# Generated by Django 4.2.2 on 2023-06-16 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='invalid_accuracy',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='valid_accuracy',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='invalid_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='valid_attempts',
            field=models.IntegerField(default=0),
        ),
    ]
